// flowConfig.js
import { MarkerType } from "@xyflow/react";

const stiliNodi = {
  cuore: {
    background: "#ffebee",
    border: "2px solid #e57373",
    color: "#c62828",
    fontWeight: "bold",
    borderRadius: "8px",
    padding: "10px",
  },
  ossigenato: {
    background: "#ffeef0",
    border: "2px solid #ef5350",
    color: "#b71c1c",
    borderRadius: "5px",
    padding: "10px",
  },
  deossigenato: {
    background: "#e3f2fd",
    border: "2px solid #42a5f5",
    color: "#0d47a1",
    borderRadius: "5px",
    padding: "10px",
  },
  scambio: {
    background: "#f3e5f5",
    border: "2px solid #ab47bc",
    color: "#4a148c",
    borderRadius: "20px",
    padding: "10px",
  },
};

export const initialNodes = [
  {
    id: "AS",
    position: { x: 320, y: 150 },
    data: { label: "Atrio Sinistro (AS)" },
    style: stiliNodi.cuore,
  },
  {
    id: "VS",
    position: { x: 320, y: 260 },
    data: { label: "Ventricolo Sinistro (VS)" },
    style: stiliNodi.cuore,
  },
  {
    id: "AD",
    position: { x: 100, y: 150 },
    data: { label: "Atrio Destro (AD)" },
    style: stiliNodi.cuore,
  },
  {
    id: "VD",
    position: { x: 100, y: 260 },
    data: { label: "Ventricolo Destro (VD)" },
    style: stiliNodi.cuore,
  },
  {
    id: "Polmoni",
    position: { x: 210, y: 20 },
    data: { label: "Polmoni" },
    style: stiliNodi.scambio,
  },
  {
    id: "Cervello",
    position: { x: -80, y: 420 },
    data: { label: "Cervello e Arti Sup." },
    style: stiliNodi.ossigenato,
  },
  {
    id: "Organi",
    position: { x: 120, y: 420 },
    data: { label: "Organi Addominali" },
    style: stiliNodi.ossigenato,
  },
  {
    id: "Reni",
    position: { x: 320, y: 420 },
    data: { label: "Reni" },
    style: stiliNodi.ossigenato,
  },
  {
    id: "ArtiInf",
    position: { x: 520, y: 420 },
    data: { label: "Arti Inferiori" },
    style: stiliNodi.ossigenato,
  },
];

const stileArcoRosso = { stroke: "#ef5350", strokeWidth: 3.5 };
const stileArcoBlu = { stroke: "#42a5f5", strokeWidth: 3.5 };

export const initialEdges = [
  {
    id: "e-ad-vd",
    source: "AD",
    target: "VD",
    label: "Tricuspide",
    style: stileArcoBlu,
    animated: true,
  },
  {
    id: "e-as-vs",
    source: "AS",
    target: "VS",
    label: "Mitrale",
    style: stileArcoRosso,
    animated: true,
  },
  {
    id: "e-vd-polm",
    source: "VD",
    target: "Polmoni",
    style: stileArcoBlu,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#42a5f5" },
  },
  {
    id: "e-polm-as",
    source: "Polmoni",
    target: "AS",
    style: stileArcoRosso,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#ef5350" },
  },
  {
    id: "e-vs-cerv",
    source: "VS",
    target: "Cervello",
    label: "Aorta",
    style: stileArcoRosso,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#ef5350" },
  },
  {
    id: "e-vs-org",
    source: "VS",
    target: "Organi",
    label: "Aorta",
    style: stileArcoRosso,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#ef5350" },
  },
  {
    id: "e-vs-reni",
    source: "VS",
    target: "Reni",
    label: "Aorta",
    style: stileArcoRosso,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#ef5350" },
  },
  {
    id: "e-vs-art",
    source: "VS",
    target: "ArtiInf",
    label: "Aorta",
    style: stileArcoRosso,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#ef5350" },
  },
  {
    id: "e-cerv-ad",
    source: "Cervello",
    target: "AD",
    style: stileArcoBlu,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#42a5f5" },
  },
  {
    id: "e-org-ad",
    source: "Organi",
    target: "AD",
    style: stileArcoBlu,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#42a5f5" },
  },
  {
    id: "e-reni-ad",
    source: "Reni",
    target: "AD",
    style: stileArcoBlu,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#42a5f5" },
  },
  {
    id: "e-art-ad",
    source: "ArtiInf",
    target: "AD",
    style: stileArcoBlu,
    animated: true,
    type: "smoothstep",
    markerEnd: { type: MarkerType.ArrowClosed, color: "#42a5f5" },
  },
];
